[package]
name = "wasm_run"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"

# DO NOT PLACE ANY BLOCKS BENEATH DEPENDENCIES
# (This will break the auto-generation)
